In [1]:
from twin import dataset, metadata
from twin import embedding as emb
from twin.pipelines import embedding_metrics_all, metrics_to_df
from twin.config import REAL_WORLD_DIR

import numpy as np
import pandas as pd
import scipy.io as sio

2026-01-24 03:40:22.436 | INFO     | twin.config:<module>:11 - PROJ_ROOT path is: /home/alex/Projects/twin

In [2]:
football_graph = dataset.football_2023()
football_standing = metadata.football_2023['conference_standing']

label_map = {standing: idx for idx, standing in enumerate(set(football_standing))}
vertex_labels = [label_map[standing] for standing in football_standing]

/home/alex/Projects/twin/venv/lib/python3.14/site-packages/scipy/io/matlab/_mio.py:236: MatReadWarning: Duplicate variable name "None" in stream - replacing previous with new
Considerscipy.io.matlab.varmats_from_mat to split file into single variable files
  matfile_dict = MR.get_variables(variable_names)

In [3]:
football_metrics = embedding_metrics_all(football_graph, emb.SGtSNELayout, target=vertex_labels, n_samples=10, n_neighbors=[5,10,15,20])

In [4]:
football_dfs = metrics_to_df(football_metrics)

In [5]:
football_dfs['PointDistance']

               Vertex        Edge        Twin
Point type
Vertex      25.390104   48.506768   58.913724
Edge        56.896519  124.680583  142.292246

In [6]:
football_dfs['KNeighborsPreservation']

      Vertex      Edge      Twin
k
5   0.435585  0.336622  0.422038
10  0.682138  0.607461  0.674422
15  0.773767  0.734159  0.772526
20  0.803272  0.782569  0.804765

In [7]:
football_dfs['KNeighborsClassifier']

      Vertex      Edge      Twin
k
5   0.976515  0.834848  0.954545
10  0.971970  0.840909  0.956061
15  0.971212  0.830303  0.952273
20  0.970455  0.823485  0.952273

In [8]:
mnist_graph = dataset.mnist(10)
mnist_digits = metadata.mnist['digit']

In [9]:
mnist_metrics = embedding_metrics_all(mnist_graph, emb.SGtSNELayout, target=mnist_digits, n_samples=10, n_neighbors=[100,200,300,400])

In [10]:
mnist_dfs = metrics_to_df(mnist_metrics)

In [11]:
tabula_graph = dataset.tabula('liver')

s = sio.loadmat(str(REAL_WORLD_DIR / 'tabula-liver.mat'))
orig_labels = s['cell_ontology_class'][0]
extracted_labels = np.array([elem[0] for elem in orig_labels])

label_map = {label: idx for idx, label in enumerate(set(extracted_labels))}
vertex_labels = [label_map[label] for label in extracted_labels]

In [12]:
tabula_metrics = embedding_metrics_all(tabula_graph, emb.SGtSNELayout, target=vertex_labels, n_samples=10, n_neighbors=[100,200,300,400])

In [13]:
tabula_dfs = metrics_to_df(tabula_metrics)

In [14]:
keys = ['MNIST handwritten digits', 'Tabula Sapiens Liver']
dfs = [mnist_dfs, tabula_dfs]

In [15]:
pd.concat([df['PointDistance'] for df in dfs], keys=keys, names=['Dataset'])

                                          Vertex         Edge         Twin
Dataset                  Point type
MNIST handwritten digits Vertex       308.876537   663.723897   621.260599
                         Edge         806.709828  1762.986942  1757.809765
Tabula Sapiens Liver     Vertex       792.829119   909.349361   895.083363
                         Edge        2473.018307  2875.267357  2809.290870

In [16]:
pd.concat([df['KNeighborsPreservation'] for df in dfs], keys=keys, names=['Dataset'])

                                Vertex      Edge      Twin
Dataset                  k
MNIST handwritten digits 100  0.935034  0.936170  0.908984
                         200  0.972260  0.974299  0.967410
                         300  0.980187  0.982380  0.978002
                         400  0.984324  0.986880  0.982627
Tabula Sapiens Liver     100  0.793005  0.805873  0.808776
                         200  0.873247  0.898000  0.879921
                         300  0.910935  0.934742  0.913533
                         400  0.932936  0.954086  0.934183

In [17]:
pd.concat([df['KNeighborsClassifier'] for df in dfs], keys=keys, names=['Dataset'])

                                Vertex      Edge      Twin
Dataset                  k
MNIST handwritten digits 100  0.984196  0.966444  0.984530
                         200  0.983639  0.964385  0.984307
                         300  0.983417  0.963272  0.984307
                         400  0.983250  0.962604  0.984140
Tabula Sapiens Liver     100  0.957060  0.938306  0.952007
                         200  0.956081  0.936429  0.950449
                         300  0.954823  0.934472  0.949471
                         400  0.953805  0.933373  0.947454